// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://worklnmzmgvnicxzpqdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvcmtsbm16bWd2bmljeHpwcWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDgwNjQsImV4cCI6MjA2OTMyNDA2NH0.5n2gJ_pol5yh08inSt6LUZ2-0MkhZDAkOgFHKkcgHyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});